name: build
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '!*.MD'
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: db833e039daf299e865d7fee36a77af803be4d7d7bcfd859a0250a5518d5ae5c
      with:
        coverageCommand: docker-compose run backend_sector bash -c  "yarn && yarn jest --coverage --forceExit"
